/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Dashboard;

/**
 *
 * @author kadek dwiki
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        panelContent.removeAll();
        panelContent.add(new Dashboard());
        panelContent.repaint();
        panelContent.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        dashboardMenu = new javax.swing.JLabel();
        karyawanMenu = new javax.swing.JLabel();
        tamuMenu = new javax.swing.JLabel();
        kamarMenu = new javax.swing.JLabel();
        tipeKamarMenu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        reservasiMenu = new javax.swing.JLabel();
        checkInMenu = new javax.swing.JLabel();
        checkOutMenu = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        laporanMenu = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        sideBar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("Reservasi Hotel");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setText("Manajemen");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Master Data");

        dashboardMenu.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        dashboardMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/report.png"))); // NOI18N
        dashboardMenu.setText(" Dashboard");
        dashboardMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMenuMouseClicked(evt);
            }
        });

        karyawanMenu.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        karyawanMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/employee.png"))); // NOI18N
        karyawanMenu.setText(" Data Pegawai");
        karyawanMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanMenuMouseClicked(evt);
            }
        });

        tamuMenu.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tamuMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        tamuMenu.setText(" Data Tamu");
        tamuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tamuMenuMouseClicked(evt);
            }
        });

        kamarMenu.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        kamarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hotel.png"))); // NOI18N
        kamarMenu.setText(" Data Kamar");

        tipeKamarMenu.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tipeKamarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bed.png"))); // NOI18N
        tipeKamarMenu.setText(" Data Tipe Kamar");

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Transaksi");

        reservasiMenu.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        reservasiMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/time-management.png"))); // NOI18N
        reservasiMenu.setText(" Data Reservasi");

        checkInMenu.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        checkInMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/registration-form.png"))); // NOI18N
        checkInMenu.setText(" Data Check-in");

        checkOutMenu.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        checkOutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cashier.png"))); // NOI18N
        checkOutMenu.setText(" Data Check-out");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Laporan");

        laporanMenu.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        laporanMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/report-file.png"))); // NOI18N
        laporanMenu.setText(" Buat Laporan");

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dashboardMenu)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(karyawanMenu)
                                    .addComponent(tamuMenu)
                                    .addComponent(kamarMenu)
                                    .addComponent(tipeKamarMenu)
                                    .addComponent(reservasiMenu)
                                    .addComponent(checkInMenu)
                                    .addComponent(checkOutMenu)
                                    .addComponent(laporanMenu))))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(dashboardMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(karyawanMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tamuMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kamarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipeKamarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservasiMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkInMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOutMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMenuMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        panelContent.add(new Dashboard());
        panelContent.repaint();
        panelContent.revalidate();
        
    }//GEN-LAST:event_dashboardMenuMouseClicked

    private void karyawanMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanMenuMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        panelContent.add(new Pegawai());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_karyawanMenuMouseClicked

    private void tamuMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamuMenuMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        panelContent.add(new Tamu());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_tamuMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel checkInMenu;
    private javax.swing.JLabel checkOutMenu;
    private javax.swing.JLabel dashboardMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kamarMenu;
    private javax.swing.JLabel karyawanMenu;
    private javax.swing.JLabel laporanMenu;
    private javax.swing.JPanel panelContent;
    private javax.swing.JLabel reservasiMenu;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel tamuMenu;
    private javax.swing.JLabel tipeKamarMenu;
    // End of variables declaration//GEN-END:variables
}
