/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Config.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kadek dwiki
 */
public class Pegawai extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    
    Connection con;
    DBConnection db = new DBConnection();
    DefaultTableModel tm;
    
    public Pegawai() {
        initComponents();
        connect();
        refreshTable();
        btnEdit.setVisible(false);
        btnHapus.setVisible(false);
    }
    
    public void connect(){
        con = db.connect();
    }
    
    private void refreshTable(){
        tm = new DefaultTableModel(null, new Object[]{"ID", "Nama", "Username", "Email", "Nomor Telepon", "Role"});
        tabelPegawai.setModel(tm);
        tm.getDataVector().removeAllElements();
        
        try{
            String query = "SELECT * FROM pegawai";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet result = ps.executeQuery();
            while(result.next()) {
                String id = result.getString("id");
                String nama = result.getString("nama");
                String username = result.getString("username");
                String email = result.getString("email");
                String no_telp = result.getString("no_telp");
                String role = result.getString("role");
                
                Object[] data = {
                    id,
                    nama,
                    username,
                    email,
                    no_telp,
                    role
                };
                
                tm.addRow(data);
            }
        }catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPegawai = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        textWelcome = new javax.swing.JLabel();
        textWelcome1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPegawai = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelAddPegawai = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnTambahData = new javax.swing.JButton();
        btnBatalTambah = new javax.swing.JButton();
        btnKembali = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputTelepon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        inputRole = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        panelEditPegawai = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnEditData = new javax.swing.JButton();
        btnBatalEdit = new javax.swing.JButton();
        btnKembaliEdit = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        inputEditUsername = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        inputEditNama = new javax.swing.JTextField();
        inputEditEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        inputEditTelepon = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        inputEditPassword = new javax.swing.JPasswordField();
        inputEditRole = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        inputEditId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        panelPegawai.setBackground(new java.awt.Color(255, 255, 255));
        panelPegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelPegawai.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, 742, -1));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/report.png"))); // NOI18N
        jLabel1.setText("  Data Pegawai");
        panelPegawai.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 31, -1, -1));

        textWelcome.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        textWelcome.setText("Manajemen Data Pegawai");
        panelPegawai.add(textWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, -1, -1));

        textWelcome1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        textWelcome1.setText("Halaman manajemen data pegawai digunakan untuk tambah, edit, dan hapus data pegawai");
        panelPegawai.add(textWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 137, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tabelPegawai.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tabelPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Username", "Email", "Nomor Telepon", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPegawai);

        panelPegawai.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 218, 742, 340));

        btnTambah.setBackground(new java.awt.Color(0, 180, 216));
        btnTambah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        panelPegawai.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 178, 95, -1));

        btnEdit.setBackground(new java.awt.Color(255, 179, 27));
        btnEdit.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelPegawai.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 178, 95, -1));

        btnHapus.setBackground(new java.awt.Color(249, 8, 35));
        btnHapus.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        panelPegawai.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 178, 95, -1));

        inputSearch.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        inputSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 53, 87)));
        inputSearch.setPreferredSize(new java.awt.Dimension(7, 20));
        panelPegawai.add(inputSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 200, 30));

        btnSearch.setBackground(new java.awt.Color(0, 180, 216));
        btnSearch.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("CARI");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        panelPegawai.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 70, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Klik data pada tabel untuk mengedit atau menghapus data");
        panelPegawai.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        add(panelPegawai, "card2");

        panelAddPegawai.setBackground(new java.awt.Color(255, 255, 255));
        panelAddPegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelAddPegawai.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 77, 742, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/report.png"))); // NOI18N
        jLabel2.setText("  Tambah Data Pegawai");
        panelAddPegawai.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 31, -1, -1));

        btnTambahData.setBackground(new java.awt.Color(0, 180, 216));
        btnTambahData.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnTambahData.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahData.setText("TAMBAH");
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });
        panelAddPegawai.add(btnTambahData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 605, 95, -1));

        btnBatalTambah.setBackground(new java.awt.Color(249, 8, 35));
        btnBatalTambah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnBatalTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnBatalTambah.setText("BATAL");
        btnBatalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTambahActionPerformed(evt);
            }
        });
        panelAddPegawai.add(btnBatalTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 605, 95, -1));

        btnKembali.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 180, 216));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/left-arrow.png"))); // NOI18N
        btnKembali.setText("  Kembali");
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });
        panelAddPegawai.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 128, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Masukkan Username");
        panelAddPegawai.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142, 500, -1));

        inputUsername.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));
        panelAddPegawai.add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 171, 500, 30));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Masukkan Nama");
        panelAddPegawai.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 219, 500, -1));

        inputNama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));
        panelAddPegawai.add(inputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 248, 500, 30));

        inputEmail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));
        panelAddPegawai.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 325, 500, 30));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Masukkan Email");
        panelAddPegawai.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 296, 500, -1));

        inputTelepon.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputTelepon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));
        panelAddPegawai.add(inputTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 402, 500, 30));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("Masukkan Nomor Telepon");
        panelAddPegawai.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 373, 500, -1));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setText("Masukkan Password");
        panelAddPegawai.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 500, -1));

        inputPassword.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 53, 87)));
        panelAddPegawai.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 479, 500, 30));

        inputRole.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "resepsionis", "admin" }));
        inputRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRoleActionPerformed(evt);
            }
        });
        panelAddPegawai.add(inputRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 556, 500, 30));

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setText("Pilih Role");
        panelAddPegawai.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 527, 146, -1));

        add(panelAddPegawai, "card2");

        panelEditPegawai.setBackground(new java.awt.Color(255, 255, 255));
        panelEditPegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelEditPegawai.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 77, 742, -1));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/report.png"))); // NOI18N
        jLabel3.setText("  Edit Data Pegawai");
        panelEditPegawai.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 31, -1, -1));

        btnEditData.setBackground(new java.awt.Color(0, 180, 216));
        btnEditData.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnEditData.setForeground(new java.awt.Color(255, 255, 255));
        btnEditData.setText("SIMPAN");
        btnEditData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDataActionPerformed(evt);
            }
        });
        panelEditPegawai.add(btnEditData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 605, 95, -1));

        btnBatalEdit.setBackground(new java.awt.Color(249, 8, 35));
        btnBatalEdit.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnBatalEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnBatalEdit.setText("BATAL");
        btnBatalEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalEditActionPerformed(evt);
            }
        });
        panelEditPegawai.add(btnBatalEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 605, 95, -1));

        btnKembaliEdit.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnKembaliEdit.setForeground(new java.awt.Color(0, 180, 216));
        btnKembaliEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/left-arrow.png"))); // NOI18N
        btnKembaliEdit.setText("  Kembali");
        btnKembaliEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliEditMouseClicked(evt);
            }
        });
        panelEditPegawai.add(btnKembaliEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 128, -1));

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setText("Masukkan Username");
        panelEditPegawai.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142, 500, -1));

        inputEditUsername.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));
        panelEditPegawai.add(inputEditUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 171, 500, 30));

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setText("Masukkan Nama");
        panelEditPegawai.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 219, 500, -1));

        inputEditNama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));
        panelEditPegawai.add(inputEditNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 248, 500, 30));

        inputEditEmail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));
        panelEditPegawai.add(inputEditEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 325, 500, 30));

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setText("Masukkan Email");
        panelEditPegawai.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 296, 500, -1));

        inputEditTelepon.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditTelepon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));
        panelEditPegawai.add(inputEditTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 402, 500, 30));

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel15.setText("Masukkan Nomor Telepon");
        panelEditPegawai.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 373, 500, -1));

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel16.setText("Masukkan Password");
        panelEditPegawai.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 500, -1));

        inputEditPassword.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 53, 87)));
        panelEditPegawai.add(inputEditPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 479, 500, 30));

        inputEditRole.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "resepsionis", "admin" }));
        inputEditRole.setToolTipText("");
        inputEditRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEditRoleActionPerformed(evt);
            }
        });
        panelEditPegawai.add(inputEditRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 556, 500, 30));

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel17.setText("Pilih Role");
        panelEditPegawai.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 527, 146, -1));

        inputEditId.setForeground(new java.awt.Color(255, 255, 255));
        inputEditId.setBorder(null);
        inputEditId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEditIdActionPerformed(evt);
            }
        });
        panelEditPegawai.add(inputEditId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        add(panelEditPegawai, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
       String nama = inputNama.getText();
       String username = inputUsername.getText();
       String email = inputEmail.getText();
       String telepon = inputTelepon.getText();
       String password = inputPassword.getText();
       
        try {
            if(!validateUsername()){
                return;
            }
            
            if(nama.isEmpty() || username.isEmpty() || email.isEmpty() || telepon.isEmpty() || password.isEmpty() ){
                JOptionPane.showMessageDialog(this, "Semua field harus terisi");
            } else {  
                String role = (String) inputRole.getSelectedItem();
                String query = "INSERT INTO pegawai(nama, username, email, no_telp, password, role) VALUES (?,?,?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, nama);
                ps.setString(2, username);
                ps.setString(3, email);
                ps.setString(4, telepon);
                ps.setString(5, password);
                ps.setString(6, role);
                ps.executeUpdate();

                refreshTable();
                JOptionPane.showMessageDialog(this, "Data baru berhasil ditambahkan");

                inputNama.setText("");
                inputUsername.setText("");
                inputEmail.setText("");
                inputTelepon.setText("");
                inputPassword.setText("");
                inputRole.setSelectedIndex(0);
                
                panelAddPegawai.setVisible(false);
                panelPegawai.setVisible(true);
            }
        } catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_btnTambahDataActionPerformed

    private void btnBatalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTambahActionPerformed
        inputNama.setText("");
        inputUsername.setText("");
        inputEmail.setText("");
        inputTelepon.setText("");
        inputPassword.setText("");
        inputRole.setSelectedIndex(0);  
    }//GEN-LAST:event_btnBatalTambahActionPerformed

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        panelAddPegawai.setVisible(false);
        panelPegawai.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void inputRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRoleActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tabelPegawai.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah yakin ingin menghapus data ini?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION){
            String id = tabelPegawai.getValueAt(row, 0).toString();
            try{
                String query = "DELETE FROM pegawai WHERE id=?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, id);
                int rowDeleted = ps.executeUpdate();
                
                if(rowDeleted > 0){
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    refreshTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus");
                }
                
            } catch(Exception e){
                System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
            }
            
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        panelPegawai.setVisible(false);
        panelEditPegawai.setVisible(true);
        
        int row = tabelPegawai.getSelectedRow();
        
//      untuk mendapatkan nilai dari masing masing kolom pada tabel model
        inputEditId.setText(tm.getValueAt(row, 0).toString());
        inputEditNama.setText(tm.getValueAt(row, 1).toString());
        inputEditUsername.setText(tm.getValueAt(row, 2).toString());
        inputEditEmail.setText(tm.getValueAt(row, 3).toString());
        inputEditTelepon.setText(tm.getValueAt(row, 4).toString());
        String role = tm.getValueAt(row, 5).toString();
        if(role.equals("resepsionis")){
            inputEditRole.setSelectedIndex(0);
        } else if(role.equals("admin")){
            inputEditRole.setSelectedIndex(1);
        }
        
//      untuk mendapatkan nilai password karena nilai password tidak ditampilkan tabel model 
        try{
            String query = "SELECT * FROM pegawai WHERE id= ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, tm.getValueAt(row, 0).toString());
            
            ResultSet result = ps.executeQuery();

            if(result.next()){
                String password = result.getString("password");
                inputEditPassword.setText(password);
            }
        } catch (Exception e){
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        panelPegawai.setVisible(false);
        panelAddPegawai.setVisible(true);

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDataActionPerformed
        String nama = inputEditNama.getText();
        String username = inputEditUsername.getText();
        String email = inputEditEmail.getText();
        String telepon = inputEditTelepon.getText();
        String password = inputEditPassword.getText();
        
        try {
            if(nama.isEmpty() || username.isEmpty() || email.isEmpty() || telepon.isEmpty() || password.isEmpty() ){
                JOptionPane.showMessageDialog(this, "Semua field harus terisi");
            } else{
                int editId = Integer.parseInt(inputEditId.getText());
                String role = (String) inputEditRole.getSelectedItem();
                String query = "UPDATE pegawai SET nama=?, username=?, email=?, no_telp=?, password=?, role=? WHERE id=?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, nama);
                ps.setString(2, username);
                ps.setString(3, email);
                ps.setString(4, telepon);
                ps.setString(5, password);
                ps.setString(6, role);
                ps.setInt(7, editId);
                ps.executeUpdate();

                refreshTable();
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui");
                panelEditPegawai.setVisible(false);
                panelPegawai.setVisible(true);

                inputEditNama.setText("");
                inputEditUsername.setText("");
                inputEditEmail.setText("");
                inputEditTelepon.setText("");
                inputEditPassword.setText("");
                inputEditRole.setSelectedIndex(0);
            }
        } catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_btnEditDataActionPerformed

    private void btnBatalEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalEditActionPerformed
        // TODO add your handling code here:
        int row = tabelPegawai.getSelectedRow();
        
//      untuk mendapatkan nilai dari masing masing kolom pada tabel model
        inputEditId.setText(tm.getValueAt(row, 0).toString());
        inputEditNama.setText(tm.getValueAt(row, 1).toString());
        inputEditUsername.setText(tm.getValueAt(row, 2).toString());
        inputEditEmail.setText(tm.getValueAt(row, 3).toString());
        inputEditTelepon.setText(tm.getValueAt(row, 4).toString());
        String role = tm.getValueAt(row, 5).toString();
        if(role.equals("resepsionis")){
            inputEditRole.setSelectedIndex(0);
        } else if(role.equals("admin")){
            inputEditRole.setSelectedIndex(1);
        }
        
//      untuk mendapatkan nilai password karena nilai password tidak ditampilkan tabel model 
        try{
            String query = "SELECT * FROM pegawai WHERE id= ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, tm.getValueAt(row, 0).toString());
            
            ResultSet result = ps.executeQuery();

            if(result.next()){
                String password = result.getString("password");
                inputEditPassword.setText(password);
            }
        } catch (Exception e){
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_btnBatalEditActionPerformed

    private void btnKembaliEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliEditMouseClicked
        panelEditPegawai.setVisible(false);
        panelPegawai.setVisible(true);
    }//GEN-LAST:event_btnKembaliEditMouseClicked

    private void inputEditRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEditRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEditRoleActionPerformed

    private void inputEditIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEditIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEditIdActionPerformed

    private void tabelPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPegawaiMouseClicked
        btnEdit.setVisible(true);
        btnHapus.setVisible(true);
    }//GEN-LAST:event_tabelPegawaiMouseClicked
    
    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        tm = new DefaultTableModel(null, new Object[]{"ID", "Nama", "Username", "Email", "Nomor Telepon", "Role"});
        tabelPegawai.setModel(tm);
        tm.getDataVector().removeAllElements();
        
        String keyword = inputSearch.getText();
        try{
            String query = "SELECT * FROM pegawai WHERE id LiKE ? OR username LIKE ? OR nama LIKE ? OR email LIKE ? OR no_telp LIKE ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");
            ps.setString(4, "%" + keyword + "%");
            ps.setString(5, "%" + keyword + "%");
            
            ResultSet result = ps.executeQuery();
            while(result.next()) {
                String id = result.getString("id");
                String nama = result.getString("nama");
                String username = result.getString("username");
                String email = result.getString("email");
                String no_telp = result.getString("no_telp");
                String role = result.getString("role");
                
                Object[] data = {
                    id,
                    nama,
                    username,
                    email,
                    no_telp,
                    role
                };
                
                tm.addRow(data);
            }
        }catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    public boolean validateUsername() {     
        boolean valid = false;
        String input = inputUsername.getText();
        String pesan = "Username sudah ada\nSilahkan masukkan username yang lain";
        
        try{
            String query = "SELECT * FROM pegawai WHERE username = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, input);
            
            ResultSet result = ps.executeQuery();
            
            if(result.next()){
                JOptionPane.showMessageDialog(null, pesan, "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else{
                valid = true;
            }
            
            
        }catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
        
        return valid;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalEdit;
    private javax.swing.JButton btnBatalTambah;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditData;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel btnKembali;
    private javax.swing.JLabel btnKembaliEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahData;
    private javax.swing.JTextField inputEditEmail;
    private javax.swing.JTextField inputEditId;
    private javax.swing.JTextField inputEditNama;
    private javax.swing.JPasswordField inputEditPassword;
    private javax.swing.JComboBox<String> inputEditRole;
    private javax.swing.JTextField inputEditTelepon;
    private javax.swing.JTextField inputEditUsername;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputNama;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JComboBox<String> inputRole;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JTextField inputTelepon;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelAddPegawai;
    private javax.swing.JPanel panelEditPegawai;
    private javax.swing.JPanel panelPegawai;
    private javax.swing.JTable tabelPegawai;
    private javax.swing.JLabel textWelcome;
    private javax.swing.JLabel textWelcome1;
    // End of variables declaration//GEN-END:variables

    
}
