/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Config.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kadek dwiki
 */
public class Tamu extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    
    Connection con;
    DBConnection db = new DBConnection();
    DefaultTableModel tm;
    
    public Tamu() {
        initComponents();
        connect();
        refreshTable();
        btnEdit.setVisible(false);
        btnHapus.setVisible(false);
    }
    
    public void connect(){
        con = db.connect();
    }
    
    private void refreshTable(){
        tm = new DefaultTableModel(null, new Object[]{"ID", "Nama", "Nomor Identitas", "Email", "Nomor Telepon", "Alamat"});
        tabelTamu.setModel(tm);
        tm.getDataVector().removeAllElements();
        
        try{
            String query = "SELECT * FROM tamu";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet result = ps.executeQuery();
            while(result.next()) {
                String id = result.getString("id");
                String nama = result.getString("nama");
                String noIdentitas = result.getString("no_identitas");
                String email = result.getString("email");
                String no_telp = result.getString("no_telp");
                String alamat = result.getString("alamat");
                
                Object[] data = {
                    id,
                    nama,
                    noIdentitas,
                    email,
                    no_telp,
                    alamat
                };
                
                tm.addRow(data);
            }
        }catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTamu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        textWelcome = new javax.swing.JLabel();
        textWelcome1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTamu = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelAddTamu = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnTambahData = new javax.swing.JButton();
        btnBatalTambah = new javax.swing.JButton();
        btnKembali = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputNoIdentitas = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inputTelepon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputAlamat = new javax.swing.JTextArea();
        panelEditTamu = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnEditData = new javax.swing.JButton();
        btnBatalEdit = new javax.swing.JButton();
        btnKembaliEdit = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        inputEditNama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        inputEditNoIdentitas = new javax.swing.JTextField();
        inputEditEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        inputEditTelepon = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        inputEditId = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputEditAlamat = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        panelTamu.setBackground(new java.awt.Color(255, 255, 255));
        panelTamu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelTamu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, 742, -1));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/report.png"))); // NOI18N
        jLabel1.setText("  Data Tamu");
        panelTamu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 31, -1, -1));

        textWelcome.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        textWelcome.setText("Manajemen Data Tamu");
        panelTamu.add(textWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 102, -1, -1));

        textWelcome1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        textWelcome1.setText("Halaman manajemen data tamu digunakan untuk tambah, edit, dan hapus data tamu yang melakukan reservasi");
        panelTamu.add(textWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 137, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tabelTamu.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tabelTamu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Nomor Identitas", "Email", "Nomor Telepon", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelTamu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTamuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTamu);

        panelTamu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 218, 742, 340));

        btnTambah.setBackground(new java.awt.Color(0, 180, 216));
        btnTambah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        panelTamu.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 178, 95, -1));

        btnEdit.setBackground(new java.awt.Color(255, 179, 27));
        btnEdit.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelTamu.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 178, 95, -1));

        btnHapus.setBackground(new java.awt.Color(249, 8, 35));
        btnHapus.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        panelTamu.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 178, 95, -1));

        inputSearch.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        inputSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 53, 87)));
        inputSearch.setPreferredSize(new java.awt.Dimension(7, 20));
        panelTamu.add(inputSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 200, 30));

        btnSearch.setBackground(new java.awt.Color(0, 180, 216));
        btnSearch.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("CARI");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        panelTamu.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 70, -1));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Klik data pada tabel untuk mengedit atau menghapus data");
        panelTamu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        add(panelTamu, "card2");

        panelAddTamu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/report.png"))); // NOI18N
        jLabel2.setText("  Tambah Data Tamu");

        btnTambahData.setBackground(new java.awt.Color(0, 180, 216));
        btnTambahData.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnTambahData.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahData.setText("TAMBAH");
        btnTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataActionPerformed(evt);
            }
        });

        btnBatalTambah.setBackground(new java.awt.Color(249, 8, 35));
        btnBatalTambah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnBatalTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnBatalTambah.setText("BATAL");
        btnBatalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTambahActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 180, 216));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/left-arrow.png"))); // NOI18N
        btnKembali.setText("  Kembali");
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Masukkan Nama");

        inputNama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Masukkan Nomor Identitas");

        inputNoIdentitas.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputNoIdentitas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));

        inputEmail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Masukkan Email");

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("Masukkan Nomor Telepon");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setText("Masukkan Alamat Lengkap");

        inputTelepon.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputTelepon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));

        inputAlamat.setColumns(20);
        inputAlamat.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputAlamat.setRows(5);
        inputAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 53, 87)));
        jScrollPane2.setViewportView(inputAlamat);

        javax.swing.GroupLayout panelAddTamuLayout = new javax.swing.GroupLayout(panelAddTamu);
        panelAddTamu.setLayout(panelAddTamuLayout);
        panelAddTamuLayout.setHorizontalGroup(
            panelAddTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddTamuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAddTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAddTamuLayout.createSequentialGroup()
                        .addComponent(btnTambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelAddTamuLayout.setVerticalGroup(
            panelAddTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddTamuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnKembali)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addComponent(inputNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(7, 7, 7)
                .addComponent(inputTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panelAddTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambahData)
                    .addComponent(btnBatalTambah)))
        );

        add(panelAddTamu, "card2");

        panelEditTamu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/report.png"))); // NOI18N
        jLabel3.setText("  Edit Data Tamu");

        btnEditData.setBackground(new java.awt.Color(0, 180, 216));
        btnEditData.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnEditData.setForeground(new java.awt.Color(255, 255, 255));
        btnEditData.setText("SIMPAN");
        btnEditData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDataActionPerformed(evt);
            }
        });

        btnBatalEdit.setBackground(new java.awt.Color(249, 8, 35));
        btnBatalEdit.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnBatalEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnBatalEdit.setText("BATAL");
        btnBatalEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalEditActionPerformed(evt);
            }
        });

        btnKembaliEdit.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnKembaliEdit.setForeground(new java.awt.Color(0, 180, 216));
        btnKembaliEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/left-arrow.png"))); // NOI18N
        btnKembaliEdit.setText("  Kembali");
        btnKembaliEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliEditMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setText("Masukkan Nama");

        inputEditNama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setText("Masukkan Nomor Identitas");

        inputEditNoIdentitas.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditNoIdentitas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));

        inputEditEmail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setText("Masukkan Email");

        inputEditTelepon.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditTelepon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 53, 87), 1, true));

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel15.setText("Masukkan Nomor Telepon");

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel16.setText("Masukkan Alamat");

        inputEditId.setForeground(new java.awt.Color(255, 255, 255));
        inputEditId.setBorder(null);
        inputEditId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEditIdActionPerformed(evt);
            }
        });

        inputEditAlamat.setColumns(20);
        inputEditAlamat.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        inputEditAlamat.setRows(5);
        inputEditAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 53, 87)));
        jScrollPane3.setViewportView(inputEditAlamat);

        javax.swing.GroupLayout panelEditTamuLayout = new javax.swing.GroupLayout(panelEditTamu);
        panelEditTamu.setLayout(panelEditTamuLayout);
        panelEditTamuLayout.setHorizontalGroup(
            panelEditTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditTamuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelEditTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEditTamuLayout.createSequentialGroup()
                        .addComponent(btnKembaliEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(inputEditId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputEditNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputEditTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEditTamuLayout.createSequentialGroup()
                        .addComponent(btnEditData, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatalEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelEditTamuLayout.setVerticalGroup(
            panelEditTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditTamuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(panelEditTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembaliEdit)
                    .addGroup(panelEditTamuLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(inputEditId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(7, 7, 7)
                .addComponent(inputEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(7, 7, 7)
                .addComponent(inputEditNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(7, 7, 7)
                .addComponent(inputEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(7, 7, 7)
                .addComponent(inputEditTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panelEditTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditData)
                    .addComponent(btnBatalEdit))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        add(panelEditTamu, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataActionPerformed
       String nama = inputNama.getText();
       String noIdentitas = inputNoIdentitas.getText();
       String email = inputEmail.getText();
       String telepon = inputTelepon.getText();
       String alamat = inputAlamat.getText();
       
        try {
            if(!validateNoIdentitas()){
                return;
            }
       
            if(nama.isEmpty() || noIdentitas.isEmpty() || email.isEmpty() || telepon.isEmpty() || alamat.isEmpty() ){
                JOptionPane.showMessageDialog(this, "Semua field harus terisi");
            }
            else {  
                String query = "INSERT INTO tamu(nama, no_identitas, email, no_telp, alamat) VALUES (?,?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, nama);
                ps.setString(2, noIdentitas);
                ps.setString(3, email);
                ps.setString(4, telepon);
                ps.setString(5, alamat);
                ps.executeUpdate();

                refreshTable();
                JOptionPane.showMessageDialog(this, "Data baru berhasil ditambahkan");

                inputNoIdentitas.setText("");
                inputNama.setText("");
                inputEmail.setText("");
                inputTelepon.setText("");
                inputAlamat.setText("");
                
                panelAddTamu.setVisible(false);
                panelTamu.setVisible(true);
            }
        } catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_btnTambahDataActionPerformed

    private void btnBatalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTambahActionPerformed
        inputNama.setText("");
        inputNoIdentitas.setText("");
        inputEmail.setText("");
        inputTelepon.setText("");
        inputAlamat.setText("");
    }//GEN-LAST:event_btnBatalTambahActionPerformed

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        panelAddTamu.setVisible(false);
        panelTamu.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tabelTamu.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah yakin ingin menghapus data ini?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION){
            String id = tabelTamu.getValueAt(row, 0).toString();
            try{
                String query = "DELETE FROM tamu WHERE id=?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, id);
                int rowDeleted = ps.executeUpdate();
                
                if(rowDeleted > 0){
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    refreshTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus");
                }
                
            } catch(Exception e){
                System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
            }
            
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        panelTamu.setVisible(false);
        panelEditTamu.setVisible(true);
        
        int row = tabelTamu.getSelectedRow();
        
//      untuk mendapatkan nilai dari masing masing kolom pada tabel model
        inputEditId.setText(tm.getValueAt(row, 0).toString());
        inputEditNama.setText(tm.getValueAt(row, 1).toString());
        inputEditNoIdentitas.setText(tm.getValueAt(row, 2).toString());
        inputEditEmail.setText(tm.getValueAt(row, 3).toString());
        inputEditTelepon.setText(tm.getValueAt(row, 4).toString());
        inputEditAlamat.setText(tm.getValueAt(row, 5).toString());
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        panelTamu.setVisible(false);
        panelAddTamu.setVisible(true);

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDataActionPerformed
        String nama = inputEditNama.getText();
        String noIdentitas = inputEditNoIdentitas.getText();
        String email = inputEditEmail.getText();
        String telepon = inputEditTelepon.getText();
        String alamat = inputEditAlamat.getText();
        
        try {
            if(nama.isEmpty() || noIdentitas.isEmpty() || email.isEmpty() || telepon.isEmpty() || alamat.isEmpty() ){
                JOptionPane.showMessageDialog(this, "Semua field harus terisi");
            } else{
                int editId = Integer.parseInt(inputEditId.getText());
                
                String query = "UPDATE tamu SET nama=?, no_identitas=?, email=?, no_telp=?, alamat=? WHERE id=?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, nama);
                ps.setString(2, noIdentitas);
                ps.setString(3, email);
                ps.setString(4, telepon);
                ps.setString(5, alamat);
                ps.setInt(6, editId);
                ps.executeUpdate();

                refreshTable();
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui");
                panelEditTamu.setVisible(false);
                panelTamu.setVisible(true);

                inputEditNoIdentitas.setText("");
                inputEditNama.setText("");
                inputEditEmail.setText("");
                inputEditTelepon.setText("");
                inputEditAlamat.setText("");
            }
        } catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_btnEditDataActionPerformed

    private void btnBatalEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalEditActionPerformed
        // TODO add your handling code here:
        int row = tabelTamu.getSelectedRow();
        
//      untuk mendapatkan nilai dari masing masing kolom pada tabel model
        inputEditId.setText(tm.getValueAt(row, 0).toString());
        inputEditNama.setText(tm.getValueAt(row, 1).toString());
        inputEditNoIdentitas.setText(tm.getValueAt(row, 2).toString());
        inputEditEmail.setText(tm.getValueAt(row, 3).toString());
        inputEditTelepon.setText(tm.getValueAt(row, 4).toString());
        inputEditAlamat.setText(tm.getValueAt(row, 5).toString());
        
    }//GEN-LAST:event_btnBatalEditActionPerformed

    private void btnKembaliEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliEditMouseClicked
        panelEditTamu.setVisible(false);
        panelTamu.setVisible(true);
    }//GEN-LAST:event_btnKembaliEditMouseClicked

    private void inputEditIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEditIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEditIdActionPerformed

    private void tabelTamuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTamuMouseClicked
        btnEdit.setVisible(true);
        btnHapus.setVisible(true);
    }//GEN-LAST:event_tabelTamuMouseClicked
    
    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        tm = new DefaultTableModel(null, new Object[]{"ID", "Nama", "Nomor Identitas", "Email", "Nomor Telepon", "Alamat"});
        tabelTamu.setModel(tm);
        tm.getDataVector().removeAllElements();
        
        String keyword = inputSearch.getText();
        try{
            String query = "SELECT * FROM tamu WHERE id LiKE ? OR nama LIKE ? OR no_identitas LIKE ? OR email LIKE ? OR no_telp LIKE ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, "%" + keyword + "%");
            ps.setString(2, "%" + keyword + "%");
            ps.setString(3, "%" + keyword + "%");
            ps.setString(4, "%" + keyword + "%");
            ps.setString(5, "%" + keyword + "%");
            
            ResultSet result = ps.executeQuery();
            while(result.next()) {
                String id = result.getString("id");
                String nama = result.getString("nama");
                String noIdentitas = result.getString("no_identitas");
                String email = result.getString("email");
                String no_telp = result.getString("no_telp");
                String alamat = result.getString("alamat");
                
                Object[] data = {
                    id,
                    nama,
                    noIdentitas,
                    email,
                    no_telp,
                    alamat
                };
                
                tm.addRow(data);
            }
        }catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    public boolean validateNoIdentitas() {     
        boolean valid = false;
        String input = inputNoIdentitas.getText();
        String pesan = "Nomor Identitas sudah terdaftar\nSilahkan cek data tamu untuk lebih lanjut";
        
        try{
            String query = "SELECT * FROM tamu WHERE no_identitas = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, input);
            
            ResultSet result = ps.executeQuery();
            
            if(result.next()){
                JOptionPane.showMessageDialog(null, pesan, "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else{
                valid = true;
            }
            
            
        }catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
        
        return valid;
    }
    
    public boolean validateEditNoIdentitas() {     
        boolean valid = false;
        String input = inputEditNoIdentitas.getText();
        String pesan = "Nomor Identitas sudah terdaftar\nSilahkan cek data tamu untuk lebih lanjut";
        
        try{
            String query = "SELECT * FROM tamu WHERE no_identitas = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, input);
            
            ResultSet result = ps.executeQuery();
            
            if(result.next()){
                JOptionPane.showMessageDialog(null, pesan, "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else{
                valid = true;
            }
            
            
        }catch(Exception e) {
            System.out.print("ERROR QUERY KE DATABASE:\n" + e + "\n\n");
        }
        
        return valid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalEdit;
    private javax.swing.JButton btnBatalTambah;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditData;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel btnKembali;
    private javax.swing.JLabel btnKembaliEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahData;
    private javax.swing.JTextArea inputAlamat;
    private javax.swing.JTextArea inputEditAlamat;
    private javax.swing.JTextField inputEditEmail;
    private javax.swing.JTextField inputEditId;
    private javax.swing.JTextField inputEditNama;
    private javax.swing.JTextField inputEditNoIdentitas;
    private javax.swing.JTextField inputEditTelepon;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNoIdentitas;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JTextField inputTelepon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelAddTamu;
    private javax.swing.JPanel panelEditTamu;
    private javax.swing.JPanel panelTamu;
    private javax.swing.JTable tabelTamu;
    private javax.swing.JLabel textWelcome;
    private javax.swing.JLabel textWelcome1;
    // End of variables declaration//GEN-END:variables

    
}
